FROM nginx:1.25.1

COPY builds/nginx.conf /etc/nginx/nginx.conf
COPY builds/selfsigned.crt /etc/nginx/selfsigned.crt
COPY builds/selfsigned.key /etc/nginx/selfsigned.key
COPY builds/client-html /usr/share/nginx/html
